name: cozy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  url_launcher: ^5.7.10
  http: ^0.12.2
  provider: ^4.3.2+3
  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.12+4
  cool_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
